"""Từ điển từ khóa đồng nghĩa ánh xạ các bảng TPC-H (Table Keyword Mapping).

Module này lưu trữ danh bạ từ khóa tiếng Việt và tiếng Anh phổ biến để phục vụ việc
nhận diện bảng dữ liệu liên quan từ câu hỏi tự nhiên của người dùng trong Schema Retriever.
"""

from typing import Final

TABLE_KEYWORD_MAP: Final[dict[str, list[str]]] = {
    "customer": [
        "khách hàng",
        "khach hang",
        "customer",
        "người mua",
        "nguoi mua",
        "thị trường",
        "thi truong",
        "phân khúc",
        "phan khuc",
        "mktsegment",
    ],
    "orders": [
        "đơn hàng",
        "don hang",
        "orders",
        "order",
        "đặt hàng",
        "dat hang",
        "ngày đặt",
        "ngay dat",
        "giao dịch",
        "giao dich",
        "trạng thái đơn",
        "orderstatus",
    ],
    "lineitem": [
        "chi tiết đơn hàng",
        "chi tiet don hang",
        "lineitem",
        "mặt hàng",
        "mat hang",
        "doanh thu",
        "doanh so",
        "revenue",
        "giá bán",
        "gia ban",
        "chiết khấu",
        "chiet khau",
        "discount",
        "thuế",
        "thue",
        "tax",
        "số lượng",
        "so luong",
        "quantity",
        "giao hàng",
        "shipdate",
        "lợi nhuận",
        "loi nhuan",
    ],
    "part": [
        "linh kiện",
        "linh kien",
        "part",
        "phụ tùng",
        "phu tung",
        "mặt hàng",
        "sản phẩm",
        "san pham",
        "thương hiệu",
        "thuong hieu",
        "brand",
        "nhà sản xuất",
        "nha san xuat",
        "loại linh kiện",
        "thép",
        "đồng",
        "nhôm",
        "hộp",
        "container",
        "giá bán lẻ",
    ],
    "supplier": [
        "nhà cung cấp",
        "nha cung cap",
        "supplier",
        "đối tác cung ứng",
        "bên bán",
        "ben ban",
        "kho cung ứng",
    ],
    "partsupp": [
        "cung ứng",
        "cung ung",
        "partsupp",
        "giá cung ứng",
        "chi phí cung cấp",
        "supplycost",
        "tồn kho",
        "ton kho",
        "số lượng tồn",
        "availqty",
    ],
    "nation": [
        "quốc gia",
        "quoc gia",
        "nation",
        "nước",
        "đất nước",
        "việt nam",
        "vietnam",
        "nhật bản",
        "japan",
        "mỹ",
        "united states",
        "hoa kỳ",
        "trung quốc",
        "china",
        "đức",
        "germany",
    ],
    "region": [
        "khu vực",
        "khu vuc",
        "region",
        "vùng",
        "vung",
        "châu á",
        "asia",
        "châu âu",
        "europe",
        "châu mỹ",
        "america",
        "trung đông",
        "middle east",
        "châu phi",
        "africa",
    ],
}


def get_table_keywords() -> dict[str, list[str]]:
    """Lấy bản sao từ điển từ khóa ánh xạ các bảng TPC-H."""
    return dict(TABLE_KEYWORD_MAP)


__all__ = [
    "TABLE_KEYWORD_MAP",
    "get_table_keywords",
]
