"""Từ điển từ khóa đồng nghĩa ánh xạ các bảng TPC-DS (Table Keyword Mapping).

Module này lưu trữ danh bạ từ khóa tiếng Việt và tiếng Anh phổ biến để phục vụ việc
nhận diện bảng dữ liệu liên quan từ câu hỏi tự nhiên của người dùng trong Schema Retriever
cho không gian 24 bảng TPC-DS.
"""

from typing import Final

TABLE_KEYWORD_MAP: Final[dict[str, list[str]]] = {
    # -------------------------------------------------------------------------
    # 1. 3 Kênh Bán hàng & 3 Kênh Đổi trả (Omnichannel Facts)
    # -------------------------------------------------------------------------
    "store_sales": [
        "bán lẻ",
        "ban le",
        "cửa hàng",
        "cua hang",
        "tại quầy",
        "tai quay",
        "tại cửa hàng",
        "tai cua hang",
        "store sales",
        "store_sales",
        "trực tiếp",
        "doanh số cửa hàng",
        "doanh thu cửa hàng",
        "hóa đơn quầy",
        "mua tại quầy",
    ],
    "store_returns": [
        "trả hàng tại quầy",
        "tra hang tai quay",
        "đổi trả cửa hàng",
        "doi tra cua hang",
        "store returns",
        "store_returns",
        "hoàn trả cửa hàng",
        "trả lại tại quầy",
        "trả hàng",
        "hoàn hàng",
    ],
    "web_sales": [
        "trực tuyến",
        "truc tuyen",
        "online",
        "website",
        "web",
        "trên mạng",
        "tren mang",
        "web sales",
        "web_sales",
        "thương mại điện tử",
        "e-commerce",
        "đặt qua web",
        "doanh số online",
        "doanh thu web",
    ],
    "web_returns": [
        "trả hàng trực tuyến",
        "tra hang truc tuyen",
        "đổi trả online",
        "doi tra online",
        "web returns",
        "web_returns",
        "hoàn trả website",
        "trả hàng web",
    ],
    "catalog_sales": [
        "danh mục",
        "danh muc",
        "catalog",
        "bưu điện",
        "buu dien",
        "đặt qua catalog",
        "bán qua catalog",
        "catalog sales",
        "catalog_sales",
        "ấn phẩm",
        "qua thư",
        "đặt qua bưu điện",
    ],
    "catalog_returns": [
        "trả hàng catalog",
        "tra hang catalog",
        "đổi trả danh mục",
        "catalog returns",
        "catalog_returns",
        "hoàn trả catalog",
    ],
    "inventory": [
        "tồn kho",
        "ton kho",
        "kho hàng",
        "kho hang",
        "inventory",
        "số lượng tồn",
        "so luong ton",
        "tồn",
        "hàng trong kho",
        "lượng tồn",
    ],
    # -------------------------------------------------------------------------
    # 2. Dimensions Cốt lõi (Item, Customer, Address, Demographics, Date, Time)
    # -------------------------------------------------------------------------
    "item": [
        "sản phẩm",
        "san pham",
        "mặt hàng",
        "mat hang",
        "hàng hóa",
        "hang hoa",
        "item",
        "product",
        "danh mục hàng",
        "loại hàng",
        "thương hiệu",
        "thuong hieu",
        "brand",
        "giá niêm yết",
        "ngành hàng",
        "category",
        "điện tử",
        "thời trang",
    ],
    "customer": [
        "khách hàng",
        "khach hang",
        "người mua",
        "nguoi mua",
        "customer",
        "thành viên",
        "thanh vien",
        "họ tên khách",
        "ngày sinh",
        "email",
        "người tiêu dùng",
    ],
    "customer_address": [
        "địa chỉ",
        "dia chi",
        "bang",
        "tiểu bang",
        "tieu bang",
        "thành phố",
        "thanh pho",
        "quốc gia",
        "tỉnh",
        "address",
        "state",
        "city",
        "street",
        "quận huyện",
        "zip",
        "california",
        "texas",
        "new york",
    ],
    "customer_demographics": [
        "nhân khẩu học",
        "nhan khau hoc",
        "giới tính",
        "gioi tinh",
        "hôn nhân",
        "hon nhan",
        "nam",
        "nữ",
        "học vấn",
        "hoc van",
        "gender",
        "marital status",
        "tín dụng",
        "người phụ thuộc",
    ],
    "household_demographics": [
        "hộ gia đình",
        "ho gia dinh",
        "thu nhập hộ",
        "số người trong nhà",
        "xe cộ hộ gia đình",
        "quy mô gia đình",
        "household",
    ],
    "income_band": [
        "khung thu nhập",
        "khung thu nhap",
        "mức thu nhập",
        "muc thu nhap",
        "dải thu nhập",
        "income band",
        "thu nhập",
    ],
    "date_dim": [
        "ngày",
        "ngay",
        "tháng",
        "thang",
        "năm",
        "nam",
        "quý",
        "quy",
        "thời gian",
        "thoi gian",
        "date",
        "year",
        "month",
        "quarter",
        "cuối tuần",
        "ngày lễ",
        "mùa",
        "hôm nay",
        "thứ",
    ],
    "time_dim": [
        "giờ",
        "gio",
        "phút",
        "phut",
        "giây",
        "giay",
        "buổi sáng",
        "buổi chiều",
        "time",
        "hour",
        "minute",
        "ca làm",
        "khung giờ",
    ],
    # -------------------------------------------------------------------------
    # 3. Channel & Operation Dimensions
    # -------------------------------------------------------------------------
    "store": [
        "cửa hàng",
        "cua hang",
        "chi nhánh",
        "chi nhanh",
        "store",
        "quản lý cửa hàng",
        "vị trí cửa hàng",
        "siêu thị",
        "địa điểm bán",
    ],
    "call_center": [
        "trung tâm cuộc gọi",
        "trung tam cuoc goi",
        "tổng đài",
        "tong dai",
        "call center",
        "chăm sóc khách hàng",
        "bán qua điện thoại",
        "điện thoại viên",
    ],
    "catalog_page": [
        "trang danh mục",
        "trang catalog",
        "catalog page",
        "số trang",
        "kỳ phát hành",
    ],
    "web_page": [
        "trang web",
        "trang web",
        "web page",
        "đường dẫn",
        "trang chủ",
        "url",
        "loại trang",
    ],
    "web_site": [
        "website công ty",
        "website",
        "web site",
        "tên miền",
        "cổng thông tin",
    ],
    "warehouse": [
        "nhà kho",
        "nha kho",
        "tổng kho",
        "tong kho",
        "kho chứa",
        "warehouse",
        "diện tích kho",
        "kho xuất hàng",
    ],
    "ship_mode": [
        "phương thức giao",
        "vận chuyển",
        "van chuyen",
        "hình thức giao hàng",
        "ship mode",
        "giao hỏa tốc",
        "chuyển phát",
        "đơn vị vận chuyển",
        "giao hàng",
    ],
    "promotion": [
        "khuyến mãi",
        "khuyen mai",
        "ưu đãi",
        "uu dai",
        "giảm giá",
        "giam gia",
        "chương trình khuyến mãi",
        "promotion",
        "voucher",
        "campaign",
        "chiết khấu",
    ],
    "reason": [
        "lý do",
        "ly do",
        "nguyên nhân",
        "nguyen nhan",
        "lý do đổi trả",
        "reason",
        "nguyên nhân hoàn hàng",
    ],
}


def get_table_keywords() -> dict[str, list[str]]:
    """Lấy bản sao từ điển từ khóa ánh xạ 24 bảng TPC-DS."""
    return dict(TABLE_KEYWORD_MAP)


__all__ = [
    "TABLE_KEYWORD_MAP",
    "get_table_keywords",
]
