"""Shortcut module re-exporting all prompts from src.agents.prompts."""

from src.agents.prompts import (
    DIALECT_RULES_MAP,
    ERROR_DIAGNOSTIC_HUMAN_PROMPT,
    ERROR_DIAGNOSTIC_PROMPT,
    ERROR_DIAGNOSTIC_SYSTEM_PROMPT,
    SCHEMA_RETRIEVER_HUMAN_PROMPT,
    SCHEMA_RETRIEVER_PROMPT,
    SCHEMA_RETRIEVER_SYSTEM_PROMPT,
    SQL_GENERATOR_HUMAN_PROMPT,
    SQL_GENERATOR_PROMPT,
    SQL_GENERATOR_RETRY_HUMAN_PROMPT,
    SQL_GENERATOR_RETRY_PROMPT,
    SQL_GENERATOR_SYSTEM_PROMPT,
    SUPPORTED_DIALECTS,
    get_dialect_rules,
    transpile_sql,
)

__all__ = [
    "DIALECT_RULES_MAP",
    "ERROR_DIAGNOSTIC_HUMAN_PROMPT",
    "ERROR_DIAGNOSTIC_PROMPT",
    "ERROR_DIAGNOSTIC_SYSTEM_PROMPT",
    "SCHEMA_RETRIEVER_HUMAN_PROMPT",
    "SCHEMA_RETRIEVER_PROMPT",
    "SCHEMA_RETRIEVER_SYSTEM_PROMPT",
    "SQL_GENERATOR_HUMAN_PROMPT",
    "SQL_GENERATOR_PROMPT",
    "SQL_GENERATOR_RETRY_HUMAN_PROMPT",
    "SQL_GENERATOR_RETRY_PROMPT",
    "SQL_GENERATOR_SYSTEM_PROMPT",
    "SUPPORTED_DIALECTS",
    "get_dialect_rules",
    "transpile_sql",
]
